version: "3.9"

services:
  backend:
    image: eclipse-temurin:21-jdk
    container_name: lern-hub-backend
    working_dir: /app
    volumes:
      - ./learn_hub-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"

  frontend:
    image: nginx:stable-alpine
    container_name: lern-hub-frontend
    volumes:
      - ./browser:/usr/share/nginx/html
    ports:
      - "8081:80"