name: Debian 12 Server Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Build Angular Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npx ng build Lern-Hub --configuration production

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.4'

      - name: Build Spring Boot JAR
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests

      - name: Prepare Deployment folder
        run: |
          mkdir -p deploy
          cp -r frontend/dist/lern-hub/* deploy/ 2>/dev/null || echo "No Angular output"
          cp backend/target/learn_hub-0.0.1-SNAPSHOT.jar deploy/ 2>/dev/null || echo "JAR not found"
          cp docker-compose.yml deploy/ 2>/dev/null || echo "No docker-compose.yml"

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: /opt/lern-hub
          strip_components: 0

      - name: Restart Docker on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/lern-hub
            docker compose down
            docker compose up --build -d